export const ROAD_CONFIG = {
  road: {
    label: 'Rua',
    speed: 1,
    capacity: 5,
    buildCost: 10,
    removeCost: 5,
    pathCost: 10,
  },
  avenue: {
    label: 'Avenida',
    speed: 1.55,
    capacity: 12,
    buildCost: 25,
    removeCost: 8,
    pathCost: 6,
  },
  roundabout: {
    label: 'Rotatória',
    speed: 0.85,
    capacity: 18,
    buildCost: 90,
    removeCost: 18,
    pathCost: 5,
  },
  roadTunnel: {
    label: 'Túnel 2 faixas',
    speed: 1.12,
    capacity: 6,
    buildCost: 22,
    portalCost: 90,
    removeCost: 18,
    pathCost: 7,
  },
  avenueTunnel: {
    label: 'Túnel 4 faixas',
    speed: 1.65,
    capacity: 14,
    buildCost: 48,
    portalCost: 160,
    removeCost: 30,
    pathCost: 4,
  },
} as const;
