import type { Vec2 } from './city.types';

export type CarStatus = 'moving' | 'stopped' | 'arrived' | 'no_route';
export type TrafficState = 'moving' | 'queued' | 'intersection' | 'turning';
export type CarLifecyclePhase = 'spawnExit' | 'driving' | 'destinationEntry';
export type TravelDirection = 'north' | 'south' | 'east' | 'west';
export type IntersectionReason = 'signal_red' | 'signal_yellow' | 'unsignalized_queue' | 'right_turn_free' | 'box_occupied' | 'exit_blocked' | 'roundabout_yield' | 'roundabout_gap';

export type Car = {
  id: string;
  originBuildingId: string;
  destinationBuildingId: string;
  x: number;
  y: number;
  currentTileX: number;
  currentTileY: number;
  route: Vec2[];
  routeIndex: number;
  progressToNext: number;
  baseSpeed: number;
  currentSpeed: number;
  targetSpeed: number;
  acceleration: number;
  braking: number;
  desiredSpeed: number;
  laneOffset: Vec2;
  laneIndex: number;
  laneCount: number;
  laneSide: -1 | 1;
  waitTimer: number;
  intersectionStopKey?: string;
  intersectionWaitSeconds: number;
  lastIntersectionKey?: string;
  priorityToken: number;
  gridlockEscapeSeconds: number;
  insideIntersectionSeconds: number;
  intersectionQueuePosition?: number;
  intersectionQueueLength?: number;
  intersectionReason?: IntersectionReason;
  turnSlowdown: number;
  blockedByCarId?: string;
  trafficState: TrafficState;
  lifecyclePhase: CarLifecyclePhase;
  lifecycleProgress: number;
  direction: TravelDirection;
  status: CarStatus;
  travelTime: number;
  estimatedTime: number;
  delay: number;
  stuckSeconds: number;
  immobileSeconds: number;
  rerouteCooldownSeconds: number;
  rerouteCount: number;
  repeatedRerouteCount: number;
  lastRouteSignature?: string;
  lastRerouteReason?: string;
  signalTransitionGraceSeconds: number;
  signalTransitionKey?: string;
};
